name: Publish Docker images
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get Tag
        id: tag
        run: echo ::set-output name=TAG::$(echo $GITHUB_REF | cut -d / -f 3)
      # Setup docker build image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # Login to dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Push Dev API Gateway Image
      - name: Push Dev API Gateway to Dockerhub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            nitricimages/dev-api-gateway:latest
            nitricimages/dev-api-gateway:${{ steps.tag.outputs.TAG }}
